# Generated by Django 4.0.5 on 2022-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('movie_img', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('content', models.TextField()),
                ('grade', models.FloatField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
